services:
  monitor-service:
    build:
      context: ../..
      dockerfile: monitor-service/deploy/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONITOR_DB_PATH: /app/data/monitor.db
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
